# 넘파이(NumPy) : 파이썬에서 숫자 계산을 빠르고 쉽게 해주는 라이브러리 -> 배열 계산

In [ ]:
a=[1,2,3]
b=[4,5,6]
#print(a+b) -> a=[1,2,3] [1, 2, 3, 4, 5, 6]



[1, 2, 3, 4, 5, 6]


In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

# a+b -> array([5, 7, 9])
# np.array([]) => 리스트처럼 보이지만 실제로는 수학용 배열, 모든 원소가 같은 타입





[6 7 8]


In [ ]:
import numpy as np

# 1차원 npArray 생성
np.array([1,2,3,4]) 


arr1=np.array([1,2,3,4]) # numpy 배열 ,<class 'numpy.ndarray'>
arr2=[1,2,3,4]           # 일반 리스트 ,<class 'list'>

print(type(arr1))
print(type(arr2))

<class 'numpy.ndarray'>
<class 'list'>


In [9]:
# 1차원 배열 : 숫자가 한 줄로 늘어선 형태
# 2차원 배열 : 숫자가 가로와 세로로 된 표 모양
# 3차원 배열 : 2차원 배열이 여러 장 겹친 입체 모양
import numpy as np

# 2차원 배열 nDArray 생성
# 1차원 배열 2개가 리스트로 묶인 형태

arr2= np.array([[1,2,3,4],
               [5,6,7,8]])


arr3= np.array([[[1,2,3,4],[1,2,3,4]],
               [[1,2,3,4],[1,2,3,4]]])


print(f"2차원 배열: {arr2}")
print(f"3차원 배열: {arr3}")

2차원 배열: [[1 2 3 4]
 [5 6 7 8]]
3차원 배열: [[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]


In [ ]:
import numpy as np


a= np.array([1,2,3,4])

print(a+1)
print(a*2)
print(a**2)
# for 문을 안쓰고 계산 가능

[2 3 4 5]
[2 4 6 8]
[ 1  4  9 16]


In [ ]:
import numpy as np


arr1 =np.array([1,2,3,4])
arr2 =np.array([[1,2,3,4],
                [5,6,7,8]])
arr3= np.array([[[1,2,3,4],[5,6,7,8]],
               [[1,2,3,4],[5,6,7,8]]])

# ndim :배열의 축(차원) 개수
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# ndarray.shape :  각 차원의 크기를 나타내는 정수 튜플로 포현
# (총 개수, 행 개수 ,열 개수)
print("------------------------------")
print(arr1.shape) # 1줄 4칸
print(arr2.shape) # 2줄 4칸
print(arr3.shape) # 2줄 (열) 2행 4칸
# ndarray.size : 배열의 전체 요소 수
print("------------------------------")
print(arr1.size)
print(arr2.size)
print(arr3.size)
# ndarray.dtype: 배열 요소의 데이터 값의 타입을 설명
print("------------------------------")
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
# ndarray.itemsize : 배열 원소 하나가 차지하는 메모리 크기
print("------------------------------")
print(arr1.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)

# ndarray.data : 배열의 실제 데이터가 저장된 메모리 버퍼(주소) 
# 궁금한 점: 파이썬은 실행할 때마다 랜덤으로 메모리 할당을 안하는 지? -> 실행할 때마다 주소 값이 똑같이 나오기 때문
#파이썬은 실행할 때마다 무작위로 메모리를 배정하지는 않습니다.
#작은 정수, 문자열은 캐싱되어 주소가 항상 같게 보일 수 있고,
#일반 객체는 실행할 때마다 새로 만들어져 주소가 달라집니다.
print("------------------------------")
print(arr1.data)
print(arr2.data)
print(arr3.data)

In [34]:
# ndArray T : 전치 행렬 (행/열 서로 바꾸는 것)
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
print(f"원래 배열: {arr}")
print(f"바꾼 배열: {arr.T}")


원래 배열: [[1 2 3]
 [4 5 6]]
바꾼 배열: [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# ndArray.flatten() : 1차원으로 펼치기
arr=np.array([[1,2,3],[4,5,6]])
print(f"원래 배열: {arr}")
print(f"바꾼 배열: {arr.flatten()}")

# flatten() 은 복사본을 만든다.
flat=arr.flatten()
flat[0]=100
print(f"배열 출력: {arr}")
print(flat[0])


In [ ]:
# ndArray.reshape() : 배열 모양 바꾸기

arr=np.array([1,2 ,3 ,4 ,5, 6])
print(f"원래 배열: {arr}")

# reshape 할 때 원본과 size가 같아야 함 -> 원소 개     수 = size 개수
arr2=arr.reshape(2,3)   # 2행(가로) 3열(세로)로 반환
print(arr2)

원래 배열: [1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
# ndArray.sum() : 합계 구하기
# axis : 어느 축을 기준으로 계산할 건지
# axis 옵션 
# axis =0 : 열 (세로 축) 방향 합
# axis =1 : 행 (가로 축) 방향 합 

arr=np.array([[1,2,3],
              [4,5,6]])

print('전체 합', arr.sum())
print('열 방향 합 (axis=0) :',arr.sum(axis=0))
print('행 방향 합 (axis=1) :',arr.sum(axis=1))




전체 합 21
열 방향 합 (axis=0) : [5 7 9]
행 방향 합 (axis=1) : [ 6 15]


In [43]:
# ndArray.mean() : 평균 구하기
# axis 옵션 
# axis =0 : 열 (세로 축) 방향 합
# axis =1 : 행 (가로 축) 방향 합 
arr=np.array([[1,2,3],
              [4,5,6]])

print('전체 평균', arr.mean())
print('열 방향 합의 평균 (axis=0) :',arr.mean(axis=0))
print('행 방향 합의 평균 (axis=1) :',arr.mean(axis=1))

전체 평균 3.5
열 방향 합의 평균 (axis=0) : [2.5 3.5 4.5]
행 방향 합의 평균 (axis=1) : [2. 5.]


In [47]:
# ndArray.min () : 최소 값
# ndArray.max () : 최대 값
# axis 옵션 
# axis =0 : 열 (세로 축) 방향 
# axis =1 : 행 (가로 축) 방향 



arr=np.array([[1,2,3],
              [4,5,6]])
print('전체 최대 값', arr.max())
print('전체 최소 값', arr.min())
print('열 방향 최대 값 (axis=0) :',arr.max(axis=0))
print('열 방향 최소 값 (axis=0) :',arr.min(axis=0))



print('행 방향 최대 값 (axis=1) :',arr.max(axis=1))
print('행 방향 최소 값 (axis=1) :',arr.min(axis=1))

전체 최대 값 6
전체 최소 값 1
열 방향 최대 값 (axis=0) : [4 5 6]
열 방향 최소 값 (axis=0) : [1 2 3]
행 방향 최대 값 (axis=1) : [3 6]
행 방향 최소 값 (axis=1) : [1 4]


In [48]:
'''
1) np.zeros(shape) 
-> 지정한 모양으로 배열을 만들고 ,모든 원소를 0으로 채운다.
-> 주로 초기 값이 0인 배열이 필요할 때 사용 (누적합, 버퍼, 마스크)
-> shape은 튜플로 넣음 : (행, 열, 층) 등
'''

# 3행 4열의 2차원 배열 생성 , 원소 값은 전부 0
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
'''
2) np.ones(shape)
-> 지정한 모양으로 배열을 만들고 , 모든 원소를 1로 채운다
'''


# 3행 4열의 2차원 배열 생성 , 원소 값은 전부 0
np.ones((2,3,4)) # => 2층, 각 층은 3행 4열

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
'''
3) np.full(shape,full_value)
-> 지정한 모양으로 배열을 만들고 , 모든 원소를 특정 값으로 채운다
'''

np.full((4,4),3) # => 4행 4열 배열에서 모든 원소 값을 3으로

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [ ]:
'''
4) *_like 계열 : np.zeros_like / np.ones_like / np.full_like
    - like 말 그대로 다른 배열을 보고 똑같이 따라 만듦
    - 기존 배열 모양을 가져와서 새 배열 생성
* 장점
    - shape을 매번 직접 적을 필요가 없음
'''


arr2= np.array([[1,2,3,4],
               [5,6,7,8]])
np.zeros_like(arr2)
np.ones_like(arr2)
np.full_like(arr2,2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
import numpy as np

# np.random 모듈은 다양한 난수 생성 기능 

'''
1) randint(시작 값, 끝 값 ,size)
지정 범위 안에서 정수형 난수 생성
 -> 시작 값 이상
 -> 끝 값 미만 (끝 값은 포함되지 않음)
 -> size는 생성할 배열의 모양
'''

np.random.randint(-100,100,(2,3)) # -100 이상 , 100 미만 , 2행 3열

'''
2) seed(숫자)
난수 생성의 초기 상태 고정
같은 seed를 주면 항상 같은 난수 결과가 나옴
'''
np.random.seed(5) # 난수 생성 기준을 1로 고정
np.random.randint(-100,100,(2,3))
# seed=1 기준으로 항상 같은 난수 배열이 생성됨
np.random.randint(0,10,(2,3,3))


array([[[4, 7, 0],
        [0, 7, 1],
        [5, 7, 0]],

       [[1, 4, 6],
        [2, 9, 9],
        [9, 9, 1]]], dtype=int32)

In [ ]:
import numpy as np

# 인덱싱(indexing) : 특정 위치에 있는 하나의 원소 값을 가져오는 방법
# 슬라이싱(Slicing) : 일정 범위를 잘라서 여러 값을 가져오는 방법


arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],
               [5,6,7,8]])

# 1차원 배열 인덱싱
print('파이썬 기본 리스트 예시')
li=[1,2,3,4]
print(li[0])

print('1차원 배열 인덱싱')
print(arr1[0])
# [시작: 끝-1: 보폭]
print('1차원 배열 슬라이싱')
print(arr1[1:3:])



print('2차원 배열 인덱싱')
print(arr2[1,2])
print('2차원 배열 슬라이싱')
# [행 범위, 열 범위]

print(arr2[1:2,1:3])


# 1 2 3 4
# 5 6 7 8


# Fancy 인덱싱: 인덱스 번호를 리스트 / 배열로 여러 개 전달
print('1차원 배열 fancy 인덱싱')
print(arr1[[0,1,3]]) 

print('2차원 배열 fancy 인덱싱')
print(arr2[[0,1],[1,3]]) 


print('')

파이썬 기본 리스트 예시
1
1차원 배열 인덱싱
1
1차원 배열 슬라이싱
[2 3]
2차원 배열 인덱싱
7
2차원 배열 슬라이싱
[[6 7]]
1차원 배열 fancy 인덱싱
[1 2 4]
2차원 배열 fancy 인덱싱
[2 8]
